<?php

namespace App\Http\TkTk;


class SeederExtension {
    /**
     * Messages for app logs
     *
     * @var array
     */
    public static $obj2sell = [
        'Computadora', 
        'PC', 
        'TV', 
        'Pulsera', 
        'La Moto de Cuevas', 
        'Moto', 
        'Choimenea', 
        'Blumer', 
        'Laptop',
        'Camisa', 
        'Celular',
    ];

    public static $brand = [
        'LG', 
        'LeEco', 
        'Lenovo', 
        'Samsung', 
        'Mercedes Benz', 
        'Asus', 
        'Zusuki', 
        'Yutong',
        'Okley',
        'Batos',
        'Fantini',
    ];

    public static $color = [
        'azul', 
        'carmelita', 
        'naranja', 
        'negro',
        'carmesi',
        'fusia',
        'canela',
        'rojo',
        'verde',
    ];

    public static $countries = [
         'Afghanistan',
         'African Union',
         'Aland',
         'Albania',
         'Alderney',
         'Algeria',
         'American Samoa',
         'Andorra',
         'Angola',
         'Anguilla',
         'Antarctica',
         'Antigua & Barbuda',
         'Arab League',
         'Argentina',
         'Armenia',
         'Aruba',
         'ASEAN',
         'Australia',
         'Austria',
         'Azerbaijan',
         'Bahamas',
         'Bahrain',
         'Bangladesh',
         'Barbados',
         'Basque Country',
         'Belarus',
         'Belgium',
         'Belize',
         'Benin',
         'Bermuda',
         'Bhutan',
         'Bolivia',
         'Bonaire-Sint Eustatius-and-Saba',
         'Bosnia & Herzegovina',
         'Botswana',
         'Bouvet',
         'Brazil',
         'British Indian Ocean Territory',
         'Brunei',
         'Bulgaria',
         'Burkina Faso',
         'Burundi',
         'Cambodja',
         'Cameroon',
         'Canada',
         'Cape Verde',
         'CARICOM',
         'Catalonia',
         'Cayman Islands',
         'Central African Republic',
         'Chad',
         'Chile',
         'China',
         'Christmas',
         'CIS',
         'Cocos (Keeling)',
         'Colombia',
         'Commonwealth',
         'Comoros',
         'Congo-Brazzaville',
         'Congo-Kinshasa',
         'Cook Islands',
         'Costa-Rica', "Cote d'Ivoire.png", 'Croatia',
         'Cuba',
         'Curacao',
         'Cyprus',
         'Czech Republic',
         'Denmark',
         'Djibouti',
         'Dominica',
         'Dominican-Republic',
         'Egypt',
         'El Salvador',
         'England',
         'Equador',
         'Equatorial Guinea',
         'Eritrea',
         'Estonia',
         'Ethiopia',
         'European Union',
         'Falkland (Malvinas)',
         'FAO',
         'Faroes',
         'Fiji',
         'Finland',
         'France',
         'French Southern and Antarctic Lands',
         'French-Guiana',
         'Gabon',
         'Galicia',
         'Gambia',
         'Georgia',
         'Germany',
         'Ghana',
         'Gibraltar',
         'Greece',
         'Greenland',
         'Grenada',
         'Guadeloupe',
         'Guam',
         'Guatemala',
         'Guernsey',
         'Guinea-Bissau',
         'Guinea',
         'Guyana',
         'Haiti',
         'Heard Island and McDonald',
         'Honduras',
         'Hong Kong',
         'Hungary',
         'IAEA',
         'Iceland',
         'IHO',
         'India',
         'Indonesia',
         'Iran',
         'Iraq',
         'Ireland',
         'Islamic Conference',
         'Isle of Man',
         'Israel',
         'Italy',
         'Jamaica',
         'japan',
         'Jersey',
         'Jordan',
         'Kazakhstan',
         'Kenya',
         'Kiribati',
         'Kosovo',
         'Kuwait',
         'Kyrgyzstan',
         'Laos',
         'Latvia',
         'Lebanon',
         'Lesotho',
         'Liberia',
         'Libya',
         'Liechtenstein',
         'Lithuania',
         'Luxembourg',
         'Macao',
         'Macedonia',
         'Madagascar',
         'Malawi',
         'Malaysia',
         'Maldives',
         'Mali',
         'Malta',
         'Marshall Islands',
         'Martinique',
         'Mauritania',
         'Mauritius',
         'Mayotte',
         'Mexico',
         'Micronesia',
         'Moldova',
         'Monaco',
         'Mongolia',
         'Montenegro',
         'Montserrat',
         'Morocco',
         'Mozambique',
         'Myanmar(Burma)',
         'Namibia',
         'NATO',
         'Nauru',
         'Nepal',
         'Netherlands Antilles',
         'Netherlands',
         'New Caledonia',
         'New Zealand',
         'Nicaragua',
         'Niger',
         'Nigeria',
         'Niue',
         'Norfolk',
         'North Korea',
         'Northern Cyprus',
         'Northern Ireland',
         'Northern Mariana',
         'Norway',
         'OAS',
         'OECD',
         'Olimpic Movement',
         'Oman',
         'OPEC',
         'Pakistan',
         'Palau',
         'Palestine',
         'Panama',
         'Papua New Guinea',
         'Paraguay',
         'Peru',
         'Philippines',
         'Pitcairn',
         'Poland',
         'Portugal',
         'Puerto Rico',
         'Qatar',
         'Quebec',
         'Red Cross',
         'Reunion',
         'Romania',
         'Russian Federation',
         'Rwanda',
         'Saint Barthelemy',
         'Saint Helena',
         'Saint Lucia',
         'Saint Pierre and Miquelon',
         'Saint-Martin (French)',
         'Samoa',
         'San Marino',
         'Sao Tome & Principe',
         'Saudi Arabia',
         'Scotland',
         'Senegal',
         'Serbia(Yugoslavia)',
         'Seyshelles',
         'Sierra Leone',
         'Singapore',
         'Sint-Maarten',
         'Slovakia',
         'Slovenia',
         'Solomon Islands',
         'Somalia',
         'Somaliland',
         'South Africa',
         'South Georgia and South Sandwich',
         'South Korea',
         'Southern-Sudan',
         'Spain',
         'Sri Lanka',
         'St Kitts & Nevis',
         'St Vincent & the Grenadines',
         'Sudan',
         'Suriname',
         'Svalbard and Jan Mayen',
         'Swaziland',
         'Sweden',
         'Switzerland',
         'Syria',
         'Tahiti(French Polinesia)',
         'Taiwan',
         'Tajikistan',
         'Tanzania',
         'Thailand',
         'Timor-Leste',
         'Togo',
         'Tokelau',
         'Tonga',
         'Trinidad & Tobago',
         'Tristan-da-Cunha',
         'Tunisia',
         'Turkey',
         'Turkmenistan',
         'Turks and Caicos Islands',
         'Tuvalu',
         'Uganda',
         'Ukraine',
         'UNESCO',
         'UNICEF',
         'United Arab Emirates',
         'United Kingdom(Great Britain)',
         'United Nations',
         'United States Minor Outlying',
         'United States of America(USA)',
         'Uruguay',
         'Uzbekistan',
         'Vanuatu',
         'Vatican City',
         'Venezuela',
         'Viet Nam',
         'Virgin Islands British',
         'Virgin Islands US',
         'Wales',
         'Wallis and Futuna',
         'Western Sahara',
         'WHO',
         'WTO',
         'Yemen',
         'Zambia',
         'Zimbabwe'
    ];


}